'use client';

import { useState } from 'react';

const DNS_RECORDS = [
  { name: 'web-01.local.forge',   ip: '172.18.0.12', container: 'frontend-cluster-01', icon: 'package_2', status: 'RESOLVED', expanded: true },
  { name: 'db-01.local.forge',    ip: '172.18.0.13', container: 'postgres-master-01',  icon: 'database',  status: 'RESOLVED', expanded: false },
  { name: 'cache-01.local.forge', ip: '172.18.0.14', container: 'redis-sentinel-01',   icon: 'memory',    status: 'STALE',    expanded: false },
];

const HOSTS_PREVIEW = `# Generated by LinuxForge Sim Engine
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
fe00::0         ip6-localnet

172.18.0.12     web-01.local.forge web-01
172.18.0.13     db-01.local.forge db-01
172.18.0.14     cache-01.local.forge cache-01`;

export default function DnsPage() {
  const [records, setRecords] = useState(DNS_RECORDS);
  const [search, setSearch] = useState('');

  const toggle = (i) => setRecords((prev) => prev.map((r, idx) => ({ ...r, expanded: idx === i ? !r.expanded : r.expanded })));
  const filtered = records.filter((r) => r.name.includes(search) || r.ip.includes(search) || r.container.includes(search));

  return (
    <div className="space-y-10 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="w-2 h-6 bg-[#adc6ff] rounded-full" />
            <span className="text-[#adc6ff] text-xs font-mono font-bold tracking-widest uppercase">Network Management</span>
          </div>
          <h1 className="font-['Space_Grotesk'] text-5xl font-bold tracking-tight text-[#e5e1e4]">Container DNS</h1>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex flex-col items-end mr-4">
            <span className="text-xs text-[#8c909f] uppercase tracking-wider font-semibold">Last Propagation</span>
            <span className="text-[#4cd7f6] font-mono">0.42ms ago</span>
          </div>
          <button className="flex items-center gap-2 px-6 py-3 bg-gradient-to-br from-[#adc6ff] to-[#4d8eff] text-[#002e6a] font-bold rounded-xl active:scale-95 transition-all shadow-lg shadow-[#adc6ff]/10">
            <span className="material-symbols-outlined text-xl">refresh</span>Refresh DNS
          </button>
        </div>
      </div>

      {/* Stats bento */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="col-span-1 p-6 bg-[#1c1b1d] rounded-xl border-t-2 border-[#adc6ff] relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity"><span className="material-symbols-outlined text-6xl">dns</span></div>
          <span className="text-[#8c909f] text-xs font-bold uppercase tracking-widest block mb-4">Total Records</span>
          <div className="flex items-baseline gap-2">
            <span className="font-['Space_Grotesk'] text-4xl font-bold text-[#e5e1e4]">1,284</span>
            <span className="text-[#4cd7f6] text-sm font-mono">+12</span>
          </div>
        </div>
        <div className="col-span-1 p-6 bg-[#1c1b1d] rounded-xl">
          <span className="text-[#8c909f] text-xs font-bold uppercase tracking-widest block mb-4">Query Latency</span>
          <div className="flex items-baseline gap-2">
            <span className="font-['Space_Grotesk'] text-4xl font-bold text-[#e5e1e4]">2.4</span>
            <span className="text-[#c2c6d6] text-sm font-mono">ms</span>
          </div>
          <div className="mt-4 h-1 w-full bg-[#353437] rounded-full overflow-hidden">
            <div className="h-full bg-[#4cd7f6] w-3/4" />
          </div>
        </div>
        <div className="col-span-2 p-6 bg-[#1c1b1d] rounded-xl flex items-center justify-between border-l-4 border-[#d0bcff]/30">
          <div>
            <span className="text-[#8c909f] text-xs font-bold uppercase tracking-widest block mb-4">Engine Health</span>
            <div className="flex items-center gap-3">
              <div className="w-3 h-3 bg-[#4cd7f6] rounded-full animate-pulse shadow-[0_0_12px_#4cd7f6]" />
              <span className="font-['Space_Grotesk'] text-2xl font-semibold text-[#e5e1e4]">Active Node 01</span>
            </div>
          </div>
          <div className="text-right">
            <span className="text-[#8c909f] text-xs font-mono block">UPTIME</span>
            <span className="font-mono text-xl text-[#d0bcff]">254:12:04</span>
          </div>
        </div>
      </div>

      {/* DNS table */}
      <div className="bg-[#0e0e10] rounded-xl overflow-hidden shadow-2xl border border-[#424754]/10">
        <div className="p-6 border-b border-[#424754]/10 flex items-center justify-between">
          <div className="relative w-96">
            <span className="material-symbols-outlined absolute left-3 top-2.5 text-[#8c909f]">search</span>
            <input value={search} onChange={(e) => setSearch(e.target.value)} className="w-full bg-[#1c1b1d] border border-[#424754]/20 rounded-lg pl-10 pr-4 py-2 text-sm text-[#e5e1e4] focus:border-[#adc6ff]/50 outline-none transition-all" placeholder="Search records (e.g. web-01)..." />
          </div>
          <div className="flex gap-2">
            <button className="p-2 hover:bg-[#2a2a2c] rounded-lg text-[#8c909f] transition-colors"><span className="material-symbols-outlined">filter_list</span></button>
            <button className="p-2 hover:bg-[#2a2a2c] rounded-lg text-[#8c909f] transition-colors"><span className="material-symbols-outlined">file_download</span></button>
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-[#1c1b1d]/50">
                {['Record Name','IP Address','Linked Container','Status','Actions'].map((h, i) => (
                  <th key={h} className={`px-6 py-4 text-xs font-bold uppercase tracking-widest text-[#8c909f] ${i === 3 ? 'text-center' : ''} ${i === 4 ? 'text-right' : ''}`}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-[#424754]/5">
              {filtered.map((r, i) => (
                <>
                  <tr key={r.name} className="hover:bg-[#1c1b1d] transition-colors group cursor-pointer" onClick={() => toggle(i)}>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <span className={`material-symbols-outlined text-sm ${r.expanded ? 'text-[#adc6ff]' : 'text-[#424754]'}`}>arrow_forward_ios</span>
                        <span className="font-semibold text-[#e5e1e4]">{r.name}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 font-mono text-sm text-[#4cd7f6]">{r.ip}</td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2">
                        <div className="w-6 h-6 bg-[#353437] rounded flex items-center justify-center"><span className="material-symbols-outlined text-xs text-[#e5e1e4]">{r.icon}</span></div>
                        <span className="text-sm text-[#e5e1e4]">{r.container}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex justify-center">
                        <span className={`px-3 py-1 text-[10px] font-bold uppercase tracking-tighter rounded-full border ${r.status === 'RESOLVED' ? 'bg-[#4cd7f6]/10 text-[#4cd7f6] border-[#4cd7f6]/20' : 'bg-[#ffb4ab]/10 text-[#ffb4ab] border-[#ffb4ab]/20'}`}>{r.status}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <button className="p-2 text-[#8c909f] hover:text-[#adc6ff] transition-colors"><span className="material-symbols-outlined">edit</span></button>
                    </td>
                  </tr>
                  {r.expanded && (
                    <tr key={`${r.name}-exp`} className="bg-[#1c1b1d]/30">
                      <td className="px-12 py-6" colSpan={5}>
                        <div className="bg-[#0e0e10] p-6 rounded-xl border border-[#424754]/10 shadow-inner">
                          <div className="flex items-center justify-between mb-4">
                            <div className="flex items-center gap-2">
                              <span className="material-symbols-outlined text-[#d0bcff]">terminal</span>
                              <span className="text-xs font-bold uppercase tracking-widest text-[#8c909f]">Preview: /etc/hosts configuration</span>
                            </div>
                            <span className="text-[10px] text-[#424754] font-mono">MD5: a8c92b...12f</span>
                          </div>
                          <pre className="font-mono text-sm text-[#d0bcff] leading-relaxed bg-black/20 p-4 rounded-lg overflow-x-auto whitespace-pre-wrap">
                            <span className="text-[#424754]"># Generated by LinuxForge Sim Engine</span>{'\n'}
                            {'127.0.0.1       localhost\n::1             localhost ip6-localhost\n\n'}
                            <span className="text-[#adc6ff]">172.18.0.12     web-01.local.forge web-01</span>{'\n'}
                            <span className="text-[#4cd7f6]">172.18.0.13     db-01.local.forge db-01</span>{'\n'}
                            <span className="text-[#d0bcff]">172.18.0.14     cache-01.local.forge cache-01</span>
                          </pre>
                        </div>
                      </td>
                    </tr>
                  )}
                </>
              ))}
            </tbody>
          </table>
        </div>
        <div className="p-6 bg-[#1c1b1d] border-t border-[#424754]/10 flex items-center justify-between">
          <span className="text-sm text-[#8c909f]">Showing {filtered.length} of 1,284 records</span>
          <div className="flex items-center gap-4">
            <button className="px-4 py-2 bg-[#353437] text-[#e5e1e4] text-sm font-semibold rounded-lg hover:bg-[#424754] transition-all">Previous</button>
            <button className="px-4 py-2 bg-[#adc6ff] text-[#002e6a] text-sm font-semibold rounded-lg hover:brightness-110 transition-all">Next</button>
          </div>
        </div>
      </div>

      {/* FAB */}
      <button className="fixed bottom-8 right-8 w-14 h-14 bg-[#d0bcff] text-[#3c0091] rounded-full shadow-2xl shadow-[#d0bcff]/20 flex items-center justify-center hover:scale-110 active:scale-95 transition-all group z-50">
        <span className="material-symbols-outlined text-3xl">add</span>
        <div className="absolute right-16 px-4 py-2 bg-[#2a2a2c] text-[#e5e1e4] text-xs font-bold whitespace-nowrap rounded-lg opacity-0 group-hover:opacity-100 translate-x-4 group-hover:translate-x-0 transition-all pointer-events-none">New Record</div>
      </button>
    </div>
  );
}
